//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int log_id { get; set; }
        public int user_id { get; set; }
        public string action_type { get; set; }
        public string table_name { get; set; }
        public int record_id { get; set; }
        public string field_name { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public System.DateTime action_date { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
    
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
