//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasMeters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GasMeters()
        {
            this.MeterReadings = new HashSet<MeterReadings>();
        }
    
        public int meter_id { get; set; }
        public int apartment_id { get; set; }
        public int meter_type_id { get; set; }
        public string serial_number { get; set; }
        public System.DateTime installation_date { get; set; }
        public decimal initial_reading { get; set; }
        public System.DateTime last_verification_date { get; set; }
        public System.DateTime next_verification_date { get; set; }
        public bool is_active { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual MeterTypes MeterTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterReadings> MeterReadings { get; set; }
    }
}
