//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int invoice_id { get; set; }
        public int apartment_id { get; set; }
        public System.DateTime period { get; set; }
        public int tariff_id { get; set; }
        public decimal consumption { get; set; }
        public decimal amount { get; set; }
        public System.DateTime issue_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string status { get; set; }
        public Nullable<int> created_by { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Tariffs Tariffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
