//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReadings
    {
        public int reading_id { get; set; }
        public int meter_id { get; set; }
        public System.DateTime reading_date { get; set; }
        public decimal current_reading { get; set; }
        public decimal consumption { get; set; }
        public bool is_verified { get; set; }
        public Nullable<System.DateTime> verification_date { get; set; }
        public Nullable<int> verified_by { get; set; }
    
        public virtual GasMeters GasMeters { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
