//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeterTypes()
        {
            this.GasMeters = new HashSet<GasMeters>();
        }
    
        public int meter_type_id { get; set; }
        public string type_name { get; set; }
        public string manufacturer { get; set; }
        public int verification_period { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GasMeters> GasMeters { get; set; }
    }
}
