//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public int invoice_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public decimal amount { get; set; }
        public string payment_method { get; set; }
        public string receipt_number { get; set; }
        public Nullable<int> operator_id { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
